<?php

namespace frontend\controllers;

use common\models\Category;
use common\models\Farmer;
use common\models\Good;
use yii\web\Controller;

class GoodController extends Controller
{
    public function beforeAction($action)
    {
        $session = \Yii::$app->session;
        $cart = $session->get('cart');
        if ($cart === null) {
            $session->set('cart', []);
        }
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }


    public function actionCatalog()
    {
        return $this->render('catalog');
    }

    public function actionFullList()
    {
        $this->layout = 'empty';
        $f_ids = \Yii::$app->request->post('f_ids'); //$_POST['f_ids'];
        $c_ids = \Yii::$app->request->post('c_ids');
        $goods = Good::find()->where(['is_visible' => 1]);
        if ($f_ids) {
            $goods = $goods->andWhere(['in', 'farmer_id', $f_ids]);
        }
        if ($c_ids) {
            $goods = $goods->andWhere(['in', 'category_id', $c_ids]);
        }
        $goods = $goods->all();
        return $this->render('full-list', compact('goods'));
    }

    public function actionView($id)
    {
        $this->layout = 'empty';
        $good = Good::findOne($id);
        $session = \Yii::$app->session;
        $cart = $session->get('cart');
        $in_cart = false;
        if (count($cart) > 0) {
            foreach ($cart as $farmer_id => $good_items) {
                if (isset($good_items[$id])) {
                    $in_cart = true;
                }
            }
        }
        return $this->render('view', compact('good', 'in_cart'));
    }

    public function actionSearchOnline($input)
    {
        $this->layout = 'empty';
        $session = \Yii::$app->session;
        $cart = $session->get('cart');
        $cart_ids = [];
        if (count($cart) > 0) {
            foreach ($cart as $item) {
                if (count($item) > 0) {
                    foreach ($item as $id => $q) {
                        $cart_ids[] = $id;
                    }
                }
            }
        }
        $goods = Good::find()->where(['like', 'name', $input])->andWhere(['is_visible' => 1])->all();
        return $this->render('search-online', compact('goods', 'cart_ids'));
    }

    public function actionSearchResult($input)
    {
        $goods = Good::find()->where(['like', 'name', $input])->andWhere(['is_visible' => 1])->all();
        $f_ids = [];
        foreach ($goods as $good) {
            if (!in_array($good->farmer_id, $f_ids)) {
                $f_ids[] = $good->farmer_id;
            }
        }
        $farmers2 = Farmer::find()->where(['like', 'name', $input])->select('id')->all();
        foreach ($farmers2 as $item) {
            if (!in_array($item->id, $f_ids)) {
                $f_ids[] = $item->id;
            }
        }
        $farmers = Farmer::findAll($f_ids);
        return $this->render('search-result', compact('goods', 'farmers', 'f_ids'));
    }

    public function actionCompany($id)
    {
        $farmer = Farmer::findOne($id);
        $categories = Category::find()->all();
        return $this->render('company', compact('farmer', 'categories'));
    }

    public function actionFarmerGoodList($farmer_id)
    {
        $this->layout = 'empty';
        $goods = Good::find()->where(['farmer_id' => $farmer_id, 'is_visible' => 1])->all();
        return $this->render('farmer-good-list', compact('goods'));
    }

    public function actionFarmerList()
    {
        $farmers = Farmer::find()->all();
        return $this->render('farmer-list', compact('farmers'));
    }

    public function actionCategoryCompaniesAndGoods($category_id)
    {
        $category = Category::findOne($category_id);
        $category_goods = $category->getGoods()->where(['is_visible' => 1])->all();
        $farmers = [];
        foreach (Farmer::find()->all() as $farmer) {
            if ($farmer->getGoods()->where(['category_id' => $category_id])->andWhere(['is_visible' => 1])->count() > 0) {
                $farmers[] = $farmer;
            }
        }

        return $this->render('category-companies-and-goods', compact('category', 'farmers', 'category_goods'));
    }


    public function actionToCart()
    {
        $good_id = $_POST['good_id'];
        $farmer_id = $_POST['farmer_id'];
        $session = \Yii::$app->session;
        $cart = $session->get('cart');
        if (isset($cart[$farmer_id])) {
            if (isset($cart[$farmer_id][$good_id])) {
                $cart[$farmer_id][$good_id]++;
            } else {
                $cart[$farmer_id][$good_id] = 1;
            }
        } else {
            $cart[$farmer_id] = [];
            $cart[$farmer_id][$good_id] = 1;
        }
        $session->set('cart', $cart);
    }

    public function actionCartCounter()
    {
        $session = \Yii::$app->session;
        $cart = $session->get('cart');
        $counter = 0;
        if (count($cart) > 0) {
            foreach ($cart as $item) {
                $counter += count($item);
            }
        }
        return $counter;
    }

}
